# ================================================================================
# BASE: Common base image with dependencies
# ================================================================================
FROM ubuntu:22.04 AS base

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git vim \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev libglvnd-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# CMAKE
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildcmake

# Setting CMake version CMake installation directory
ARG CMAKE_VERSION=3.29.0
ARG CMAKE_INSTALL_DIR=/cmake

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz && \
    tar -xzvf cmake-${CMAKE_VERSION}.tar.gz && \
    rm cmake-${CMAKE_VERSION}.tar.gz 

WORKDIR /cmake-${CMAKE_VERSION}
RUN ./bootstrap --prefix=${CMAKE_INSTALL_DIR} && \
    make -j6 && \
    make install

# Cleanup
WORKDIR / 
RUN rm -rf /cmake-${CMAKE_VERSION}

# ================================================================================
# OPENMPI
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildompi

# Copy cmake binary from buildcmake 
COPY --from=buildcmake /cmake /cmake

# Setting OMPI version OMPI installation directory
ARG OMPI_VERSION=5.0.5
ARG OMPI_INSTALL_DIR=/openmpi

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OMPI_VERSION}.tar.gz && \
    tar -xzvf openmpi-${OMPI_VERSION}.tar.gz && \
    rm openmpi-${OMPI_VERSION}.tar.gz

WORKDIR /openmpi-${OMPI_VERSION}
RUN ./configure --with-pmix --with-slurm --prefix=${OMPI_INSTALL_DIR} && \
    make -j6 all && \
    make install 

# Cleanup
WORKDIR / 
RUN rm -rf /openmpi-${OMPI_VERSION}

# ================================================================================
# VTK
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildvtk

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake 

ENV PATH="/cmake/bin:${PATH}"

# Setting VTK  version VTK installation directory
ARG VTK_VERSION=9.3.0
ARG VTK_INSTALL_DIR=/vtk

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN wget https://www.vtk.org/files/release/9.3/VTK-${VTK_VERSION}.tar.gz && \
    tar -xzvf VTK-${VTK_VERSION}.tar.gz && \
    rm VTK-${VTK_VERSION}.tar.gz

WORKDIR /build-vtk
RUN cmake -DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_BUILD_TYPE:STRING=RELEASE \
-DBUILD_EXAMPLES=OFF \
-DBUILD_TESTING=OFF \
-DVTK_USE_SYSTEM_EXPAT:BOOL=ON \
-DVTK_USE_SYSTEM_ZLIB:BOOL=ON \
-DVTK_LEGACY_REMOVE=ON \
-DVTK_Group_Rendering=OFF \
-DVTK_Group_StandAlone=OFF \
-DVTK_RENDERING_BACKEND=None \
-DVTK_WRAP_PYTHON=OFF \
-DModule_vtkChartsCore=ON \
-DModule_vtkCommonCore=ON \
-DModule_vtkCommonDataModel=ON \
-DModule_vtkCommonExecutionModel=ON \
-DModule_vtkFiltersCore=ON \
-DModule_vtkFiltersFlowPaths=ON \
-DModule_vtkFiltersModeling=ON \
-DModule_vtkIOLegacy=ON \
-DModule_vtkIOXML=ON \
-DVTK_GROUP_ENABLE_Views=NO \
-DVTK_GROUP_ENABLE_Web=NO \
-DVTK_GROUP_ENABLE_Imaging=NO \
-DVTK_GROUP_ENABLE_Qt=DONT_WANT \
-DVTK_GROUP_ENABLE_Rendering=DONT_WANT \
-DCMAKE_INSTALL_PREFIX=${VTK_INSTALL_DIR} /VTK-${VTK_VERSION} && \
    cmake --build . --parallel 4 && \
    make install

# Cleanup
WORKDIR / 
RUN rm -rf /VTK-${VTK_VERSION} build-vtk

# ================================================================================
# BOOST
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildboost

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake 

ENV PATH="/cmake/bin:${PATH}"

# Setting Boost version Boost installation directory
ARG BOOST_VERSION=1_84_0
ARG BOOST_INSTALL_DIR=/boost

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_${BOOST_VERSION}.tar.gz && \
    tar -xzvf boost_${BOOST_VERSION}.tar.gz && \
    rm boost_${BOOST_VERSION}.tar.gz

WORKDIR /boost_${BOOST_VERSION}
RUN ./bootstrap.sh --prefix=${BOOST_INSTALL_DIR} && \
    ./b2 install 

# Cleanup
WORKDIR / 
RUN rm -rf /boost_${BOOST_VERSION}

# ================================================================================
# LAPACK
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildlapack

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake 
ENV PATH="/cmake/bin:${PATH}"

# Setting lapack installation directory
ARG LAPACK_INSTALL_DIR=/tmp/lapack

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN git clone https://github.com/Reference-LAPACK/lapack.git
WORKDIR /build
RUN cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_LIBDIR=${LAPACK_INSTALL_DIR} ../lapack && \
    cmake --build . -j6 --target install

# Cleanup
WORKDIR / 
RUN rm -rf /build /lapack

# ================================================================================
# HDF5
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildhdf5

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi/

ENV PATH="/cmake/bin:/openmpi:${PATH}"

# Setting hdf5 installation directories
ARG HDF5_INSTALL_DIR=/hdf5

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
WORKDIR /hdf5build

#RUN chown -R luser:luser /hdf5build && \
#    chown -R luser:luser /usr/lib/aarch64-linux-gnu 

RUN mkdir ${HDF5_INSTALL_DIR} 
#    chown -R luser:luser ${HDF5_INSTALL_DIR}

#USER luser
RUN git clone https://github.com/HDFGroup/hdf5.git 

# Build HDF5
WORKDIR /hdf5build/build
RUN cmake -C /hdf5build/hdf5/config/cmake/cacheinit.cmake -G "Unix Makefiles" \
-DHDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16:BOOL=OFF \
-DHDF5_BUILD_JAVA:BOOL=OFF \
-DHDF5_ENABLE_PARALLEL:BOOL=ON \
-DALLOW_UNSUPPORTED:BOOL=ON \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=${HDF5_INSTALL_DIR} /hdf5build/hdf5 && \
    cmake --build . && \
    make install

# For testing
# ctest . -C --rerun-failed --output-on-failure && \

# Cleanup
#USER root
WORKDIR /
RUN rm -rf /hdf5build

# ================================================================================
# HYPRE
# ================================================================================

# Use a base image for building tools and dependencise
FROM base AS buildhypre

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildlapack /tmp/lapack /lapack/

ENV PATH="/cmake/bin:/openmpi/bin:/lapack:${PATH}"

# Setting hypre installation directory
ARG HYPRE_INSTALL_DIR=/hypre-install

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN git clone https://github.com/hypre-space/hypre.git

WORKDIR /hypre/src/
RUN ./configure --prefix=${HYPRE_INSTALL_DIR} && \
    make install 

# Cleanup
WORKDIR /
RUN rm -rf /hypre

# ================================================================================
# TRILINOS
# ================================================================================

# Use a base image for building tools and dependencise
FROM base AS buildtrilinos

# Copy all dependencies and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildboost /boost /boost
COPY --from=buildhdf5 /hdf5 /hdf5
COPY --from=buildlapack /tmp/lapack /lapack
COPY --from=buildhypre /hypre-install /hypre/

ENV PATH="/cmake/bin:/openmpi/bin:${PATH}"

# Make sure python3 is the default python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Setting hypre installation directory
ARG TRILINOS_INSTALL_DIR=/trilinos

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download, extract, install
RUN git clone https://github.com/trilinos/Trilinos.git
WORKDIR /Trilinos/build

# Build trilinos
#-DTPL_ENABLE_MUMPS=ON \
RUN cmake \
-DCMAKE_INSTALL_PREFIX=${TRILINOS_INSTALL_DIR} \
-DTPL_ENABLE_MPI=ON \
-DTPL_ENABLE_Boost=ON \
-DBoost_LIBRARY_DIRS=/boost/lib \
-DBoost_INCLUDE_DIRS=/boost/include \
-DTPL_ENABLE_BLAS=ON \
-DBLAS_LIBRARY_DIRS=/lapack \
-DTPL_ENABLE_HDF5=ON \
-DHDF5_LIBRARY_DIRS=/hdf5/lib \
-DHDF5_INCLUDE_DIRS=/hdf5/include \ 
-DTPL_ENABLE_HYPRE=ON \
-DHYPRE_LIBRARY_DIRS=/hypre/lib \
-DHYPRE_INCLUDE_DIRS=/hypre/include \
-DTPL_ENABLE_LAPACK=ON \
-DLAPACK_LIBRARY_DIRS=/lapack \
-DCMAKE_C_COMPILER=/openmpi/bin/mpicc \
-DCMAKE_CXX_COMPILER=/openmpi/bin/mpicxx \
-DCMAKE_Fortran_COMPILER=/openmpi/bin/mpif90 \
-DTrilinos_ENABLE_Epetra=ON \
-DTrilinos_ENABLE_AztecOO=ON \
-DTrilinos_ENABLE_Ifpack=ON \
-DTrilinos_ENABLE_EpetraEXT=ON \
-DTrilinos_ENABLE_Amesos=ON \
-DTrilinos_ENABLE_ML=ON \
-DTrilinos_ENABLE_MueLU=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Sacado=ON \
-DTrilinos_ENABLE_Teuchos=ON \
-DTrilinos_ENABLE_Zoltan=ON \
-DTrilinos_ENABLE_Gtest=OFF /Trilinos && \
make -j6 install

# Cleanup
WORKDIR /
RUN rm -rf Trilinos


# ================================================================================
# PETSC
# ================================================================================

# Use a base image for building tools and dependencise
FROM base AS buildpetsc

# Copy all dependencies and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildboost /boost /boost
COPY --from=buildhdf5 /hdf5 /hdf5
COPY --from=buildlapack /tmp/lapack /lapack
COPY --from=buildhypre /hypre-install /hypre/

ENV PATH="/cmake/bin:${PATH}"

# Make sure python3 is the default python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Setting petsc installation directory
ARG PETSC_INSTALL_DIR=/petsc-install

# Create new user
RUN useradd -ms /bin/bash luser

# ================================================================================
# Download and install
RUN git clone -b release https://gitlab.com/petsc/petsc.git 

# Set permission for luser
RUN chown -R luser:luser /petsc

RUN mkdir ${PETSC_INSTALL_DIR} && \
    chown -R luser:luser ${PETSC_INSTALL_DIR}

# Switch user (petsc should be installed by non-root)
USER luser

WORKDIR /petsc

# Install petsc library in $PETSC_INSTALL_DIR 
# Libraries path must be set explicitly
RUN ./configure --prefix=$PETSC_INSTALL_DIR \
--with-debugging=0 \
--with-precision=double \
--download-suitesparse \
--download-mumps \
--download-superlu \
--download-superlu_dist \
--download-ml \
--download-eigen \
--download-hypre \
--with-mpi-dir=/openmpi \
--with-blas-lib=/lapack/libblas.so \
--with-lapack-lib=/lapack/liblapack.so \
--download-scalapack \
--download-metis \
--download-parmetis \
--with-strict-petscerrorcode \
--with-mpi-compilers=1 \
COPTFLAGS='-g -O' \
FOPTFLAGS='-g -O' \
CXXOPTFLAGS='-g -O' && \
make PETSC_DIR=/petsc PETSC_ARCH=arch-linux-c-opt all && \
make PETSC_DIR=/petsc PETSC_ARCH=arch-linux-c-opt install && \
make PETSC_DIR=$PETSC_INSTALL_DIR PETSC_ARCH="" check

# Cleanup
USER root
WORKDIR /
RUN rm -rf /petsc

# ================================================================================
# GOOGLE TEST
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS buildgtest

# Copy all dependencies and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi

ENV PATH="/cmake/bin:/openmpi/bin:${PATH}"

# ================================================================================
# GTEST
RUN git clone https://github.com/google/googletest.git -b v1.14.0 
WORKDIR /googletest
RUN mkdir build    && \
    cd build       && \
    cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=OFF -DCMAKE_INSTALL_PREFIX=/google && \
    make && \
    make install

# Clenup
WORKDIR /
RUN rm -rf /googletest

# ================================================================================
# FINAL IMAGE
# ================================================================================
# Use a base image for building tools and dependencise
FROM base AS final

# Copy all libraries and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildvtk /vtk /vtk
COPY --from=buildboost /boost /boost
COPY --from=buildhdf5 /hdf5 /hdf5
COPY --from=buildlapack /tmp/lapack /lapack
COPY --from=buildhypre /hypre-install /hypre/
COPY --from=buildtrilinos /trilinos /trilinos
COPY --from=buildpetsc /petsc-install /petsc
COPY --from=buildgtest /google /google  

# ================================================================================
# CONDA
ENV CONDA_DIR /conda

# Conda environment depending on architecture
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    /bin/bash /miniconda.sh -b -p $CONDA_DIR

ENV PATH="${CONDA_DIR}/bin:${PATH}"

# Create Conda environment
RUN conda create -y -n svmultiphysics && \
    conda run -n svmultiphysics pip install pytest pytest-cov pytest-mock numpy meshio pandas

# Set libraries environment
ENV PATH="/google:/vtk:/openmpi/bin:/cmake/bin:/trilinos/lib/cmake/Trilinos:${PATH}"
ENV LD_LIBRARY_PATH="/openmpi/lib:/petsc/lib:/lapack:$LD_LIBRARY_PATH"
