# ================================================================================
# CMAKE
# ================================================================================
# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildcmake

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting CMake version CMake installation directory
ARG CMAKE_VERSION=3.29.0
ARG CMAKE_INSTALL_DIR=/cmake

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz && \
    tar -xzvf cmake-${CMAKE_VERSION}.tar.gz && \
    rm cmake-${CMAKE_VERSION}.tar.gz 

WORKDIR /cmake-${CMAKE_VERSION}
RUN ./bootstrap --prefix=${CMAKE_INSTALL_DIR} && \
    make -j6 && \
    make install

# Cleanup
WORKDIR / 
RUN rm -rf /cmake-${CMAKE_VERSION}

# ================================================================================
# OPENMPI
# ================================================================================
# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildompi

# Copy cmake binary from buildcmake 
COPY --from=buildcmake /cmake /cmake

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting OMPI version OMPI installation directory
ARG OMPI_VERSION=5.0.2
ARG OMPI_INSTALL_DIR=/openmpi

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
RUN wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${OMPI_VERSION}.tar.gz && \
    tar -xzvf openmpi-${OMPI_VERSION}.tar.gz && \
    rm openmpi-${OMPI_VERSION}.tar.gz

WORKDIR /openmpi-${OMPI_VERSION}
RUN ./configure --prefix=${OMPI_INSTALL_DIR} && \
    make -j6 all && \
    make install 

# Cleanup
WORKDIR / 
RUN rm -rf /openmpi-${OMPI_VERSION}

# ================================================================================
# VTK
# ================================================================================
# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildvtk

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake 

ENV PATH="/cmake/bin:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting VTK  version VTK installation directory
ARG VTK_VERSION=9.3.0
ARG VTK_INSTALL_DIR=/vtk

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev libglvnd-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
RUN wget https://www.vtk.org/files/release/9.3/VTK-${VTK_VERSION}.tar.gz && \
    tar -xzvf VTK-${VTK_VERSION}.tar.gz && \
    rm VTK-${VTK_VERSION}.tar.gz

WORKDIR /build-vtk
RUN cmake -DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_BUILD_TYPE:STRING=RELEASE \
-DBUILD_EXAMPLES=OFF \
-DBUILD_TESTING=OFF \
-DVTK_USE_SYSTEM_EXPAT:BOOL=ON \
-DVTK_USE_SYSTEM_ZLIB:BOOL=ON \
-DVTK_LEGACY_REMOVE=ON \
-DVTK_Group_Rendering=OFF \
-DVTK_Group_StandAlone=OFF \
-DVTK_RENDERING_BACKEND=None \
-DVTK_WRAP_PYTHON=OFF \
-DModule_vtkChartsCore=ON \
-DModule_vtkCommonCore=ON \
-DModule_vtkCommonDataModel=ON \
-DModule_vtkCommonExecutionModel=ON \
-DModule_vtkFiltersCore=ON \
-DModule_vtkFiltersFlowPaths=ON \
-DModule_vtkFiltersModeling=ON \
-DModule_vtkIOLegacy=ON \
-DModule_vtkIOXML=ON \
-DVTK_GROUP_ENABLE_Views=NO \
-DVTK_GROUP_ENABLE_Web=NO \
-DVTK_GROUP_ENABLE_Imaging=NO \
-DVTK_GROUP_ENABLE_Qt=DONT_WANT \
-DVTK_GROUP_ENABLE_Rendering=DONT_WANT \
-DCMAKE_INSTALL_PREFIX=${VTK_INSTALL_DIR} /VTK-${VTK_VERSION} && \
    cmake --build . --parallel 4 && \
    make install

# Cleanup
WORKDIR / 
RUN rm -rf /VTK-${VTK_VERSION} build-vtk

# ================================================================================
# BOOST
# ================================================================================
# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildboost

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake 

ENV PATH="/cmake/bin:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting Boost version Boost installation directory
ARG BOOST_VERSION=1_84_0
ARG BOOST_INSTALL_DIR=/boost

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_${BOOST_VERSION}.tar.gz && \
    tar -xzvf boost_${BOOST_VERSION}.tar.gz && \
    rm boost_${BOOST_VERSION}.tar.gz

WORKDIR /boost_${BOOST_VERSION}
RUN ./bootstrap.sh --prefix=${BOOST_INSTALL_DIR} && \
    ./b2 install 

# Cleanup
WORKDIR / 
RUN rm -rf /boost_${BOOST_VERSION}

# ================================================================================
# LAPACK
# ================================================================================
# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildlapack

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake 
ENV PATH="/cmake/bin:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting lapack installation directory
ARG LAPACK_INSTALL_DIR=/tmp/lapack

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
RUN git clone https://github.com/Reference-LAPACK/lapack.git
WORKDIR /build
RUN cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_LIBDIR=${LAPACK_INSTALL_DIR} ../lapack && \
    cmake --build . -j6 --target install

# Cleanup
WORKDIR / 
RUN rm -rf /build /lapack

# ================================================================================
# BLAS (USE FROM LAPACK INSTALLATION)
# ================================================================================
# Use a base image for building tools and dependencise
#FROM ubuntu:20.04 AS buildblas

# Copy cmake binary from buildcmake and set ENV
#COPY --from=buildcmake /cmake /cmake 

#ENV PATH="/cmake/bin:${PATH}"

# Any debian-based command will not prompt user-input
#ENV DEBIAN_FRONTEND=noninteractive

# Setting blas version and installation directory
#ARG BLAS_VERSION=3.12.0
#ARG BLAS_INSTALL_DIR=/blas

# Create new user
#RUN useradd -ms /bin/bash luser

# Install essentials tools
#RUN apt-get update && \
#    apt-get install -y \
#    build-essential wget git \
#    python3 gfortran default-jdk default-jre \
#    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
#    openssl libssl-dev zlib1g-dev libicu-dev && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
#RUN wget http://www.netlib.org/blas/blas-${BLAS_VERSION}.tgz && \
#    tar -xvf blas-${BLAS_VERSION}.tgz && \
#    rm blas-${BLAS_VERSION}.tgz

#WORKDIR /build
#RUN cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${BLAS_INSTALL_DIR} ../BLAS-${BLAS_VERSION} && \
#    make && \
#    make install 

# Cleanup
#WORKDIR /
#RUN rm -rf /BLAS-${BLAS_VERSION} /build

# ================================================================================
# HDF5
# ================================================================================
# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildhdf5

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi/

ENV PATH="/cmake/bin:/openmpi:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting hdf5 installation directories
ARG HDF5_INSTALL_DIR=/hdf5

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
WORKDIR /hdf5build

# setting luser permission to directories and changing user to luser
# this allows the HDF5 tests to run smoothly 
RUN chown -R luser:luser /hdf5build && \
    chown -R luser:luser /usr/lib/x86_64-linux-gnu/

RUN mkdir ${HDF5_INSTALL_DIR} && \
    chown -R luser:luser ${HDF5_INSTALL_DIR}

USER luser
RUN git clone https://github.com/HDFGroup/hdf5.git 

# Build HDF5
WORKDIR /hdf5build/build
RUN cmake -C /hdf5build/hdf5/config/cmake/cacheinit.cmake -G "Unix Makefiles" \
-DHDF5_ENABLE_PARALLEL:BOOL=ON \
-DALLOW_UNSUPPORTED:BOOL=ON \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=${HDF5_INSTALL_DIR} /hdf5build/hdf5 && \
    cmake --build . && \
    make install

# For testing
# ctest . -C --rerun-failed --output-on-failure && \

# Cleanup
USER root
WORKDIR /
RUN rm -rf /hdf5build

# ================================================================================
# HYPRE
# ================================================================================

# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildhypre

# Copy cmake binary from buildcmake and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildlapack /tmp/lapack /lapack/

ENV PATH="/cmake/bin:/openmpi/bin:/lapack:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting hypre installation directory
ARG HYPRE_INSTALL_DIR=/hypre-install

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ================================================================================
# Download, extract, install
RUN git clone https://github.com/hypre-space/hypre.git

WORKDIR /hypre/src/
RUN ./configure --prefix=${HYPRE_INSTALL_DIR} && \
    make install 

# Cleanup
WORKDIR /
RUN rm -rf /hypre

# ================================================================================
# TRILINOS
# ================================================================================

# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildtrilinos

# Copy all dependencies and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildboost /boost /boost
COPY --from=buildhdf5 /hdf5 /hdf5
COPY --from=buildlapack /tmp/lapack /lapack
COPY --from=buildhypre /hypre-install /hypre/

ENV PATH="/cmake/bin:/openmpi/bin:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting hypre installation directory
ARG TRILINOS_INSTALL_DIR=/trilinos

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# ================================================================================
# Download, extract, install
RUN git clone https://github.com/trilinos/Trilinos.git
WORKDIR /Trilinos/build

# Build trilinos
#-DTPL_ENABLE_MUMPS=ON \
RUN cmake \
-DCMAKE_INSTALL_PREFIX=${TRILINOS_INSTALL_DIR} \
-DTPL_ENABLE_MPI=ON \
-DTPL_ENABLE_Boost=ON \
-DBoost_LIBRARY_DIRS=/boost/lib \
-DBoost_INCLUDE_DIRS=/boost/include \
-DTPL_ENABLE_BLAS=ON \
-DBLAS_LIBRARY_DIRS=/lapack \
-DTPL_ENABLE_HDF5=ON \
-DHDF5_LIBRARY_DIRS=/hdf5/lib \
-DHDF5_INCLUDE_DIRS=/hdf5/include \ 
-DTPL_ENABLE_HYPRE=ON \
-DHYPRE_LIBRARY_DIRS=/hypre/lib \
-DHYPRE_INCLUDE_DIRS=/hypre/include \
-DTPL_ENABLE_LAPACK=ON \
-DLAPACK_LIBRARY_DIRS=/lapack \
-DCMAKE_C_COMPILER=/openmpi/bin/mpicc \
-DCMAKE_CXX_COMPILER=/openmpi/bin/mpicxx \
-DCMAKE_Fortran_COMPILER=/openmpi/bin/mpif90 \
-DTrilinos_ENABLE_Epetra=ON \
-DTrilinos_ENABLE_AztecOO=ON \
-DTrilinos_ENABLE_Ifpack=ON \
-DTrilinos_ENABLE_EpetraEXT=ON \
-DTrilinos_ENABLE_Amesos=ON \
-DTrilinos_ENABLE_ML=ON \
-DTrilinos_ENABLE_MueLU=ON \
-DTrilinos_ENABLE_ROL=ON \
-DTrilinos_ENABLE_Sacado=ON \
-DTrilinos_ENABLE_Teuchos=ON \
-DTrilinos_ENABLE_Zoltan=ON \
/Trilinos && \
make -j6 install

# Cleanup
WORKDIR /
RUN rm -rf Trilinos


# ================================================================================
# PETSC
# ================================================================================

# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS buildpetsc

# Copy all dependencies and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildboost /boost /boost
COPY --from=buildhdf5 /hdf5 /hdf5
COPY --from=buildlapack /tmp/lapack /lapack
COPY --from=buildhypre /hypre-install /hypre/

ENV PATH="/cmake/bin:${PATH}"

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Setting petsc installation directory
ARG PETSC_INSTALL_DIR=/petsc-install

# Create new user
RUN useradd -ms /bin/bash luser

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# By default the cmake is looking for python and not python3
# The following line creates a symbolic link python->python3 
RUN ln -s /usr/bin/python3 /usr/bin/python

# ================================================================================
# Download and install
RUN git clone -b release https://gitlab.com/petsc/petsc.git 

# Set permission for luser
RUN chown -R luser:luser /petsc

RUN mkdir ${PETSC_INSTALL_DIR} && \
    chown -R luser:luser ${PETSC_INSTALL_DIR}

# Switch user (petsc should be installed by non-root)
USER luser

WORKDIR /petsc

# Install petsc library in $PETSC_INSTALL_DIR 
# Libraries path must be set explicitly
RUN ./configure --prefix=$PETSC_INSTALL_DIR \
--with-debugging=0 \
--with-precision=double \
--download-suitesparse \
--download-mumps \
--download-superlu \
--download-superlu_dist \
--download-ml \
--download-eigen \
--download-hypre \
--with-blas-lib=/lapack/libblas.so \
--with-lapack-lib=/lapack/liblapack.so \
--download-scalapack \
--download-metis \
--download-parmetis \
--download-openmpi \
--with-strict-petscerrorcode \
COPTFLAGS='-g -O' \
FOPTFLAGS='-g -O' \
CXXOPTFLAGS='-g -O' && \
make PETSC_DIR=/petsc PETSC_ARCH=arch-linux-c-opt all && \
make PETSC_DIR=/petsc PETSC_ARCH=arch-linux-c-opt install && \
make PETSC_DIR=$PETSC_INSTALL_DIR PETSC_ARCH="" check

# Cleanup
USER root
WORKDIR /
RUN rm -rf /petsc


# ================================================================================
# FINAL IMAGE
# ================================================================================

# Use a base image for building tools and dependencise
FROM ubuntu:22.04 AS final

# Any debian-based command will not prompt user-input
ENV DEBIAN_FRONTEND=noninteractive

# Install essentials tools
RUN apt-get update && \
    apt-get install -y \
    build-essential wget git \
    python3 gfortran default-jdk default-jre \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \ 
    openssl libssl-dev zlib1g-dev libicu-dev libglvnd-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy all libraries and set ENV
COPY --from=buildcmake /cmake /cmake
COPY --from=buildompi /openmpi /openmpi
COPY --from=buildvtk /vtk /vtk
COPY --from=buildboost /boost /boost
COPY --from=buildhdf5 /hdf5 /hdf5
COPY --from=buildlapack /tmp/lapack /lapack
COPY --from=buildhypre /hypre-install /hypre/
COPY --from=buildtrilinos /trilinos /trilinos
COPY --from=buildpetsc /petsc-install /petsc

ENV PATH="/vtk:/openmpi/bin:/lapack:/cmake/bin:/trilinos/lib/cmake/Trilinos:${PATH}"
ENV LD_LIBRARY_PATH="/petsc/lib"
