set(SV_LIBS
  THIRDPARTY_METIS_INTERNAL
  THIRDPARTY_PARMETIS_INTERNAL
  THIRDPARTY_GKLIB_INTERNAL
  THIRDPARTY_TETGEN
  THIRDPARTY_TINYXML
  THIRDPARTY_ZLIB
  SVFSILS
  SVFSI_CINTERFACE
  SVFSILS_CINTERFACE
)

foreach(lib ${SV_LIBS})
  string(TOLOWER "_SIMVASCULAR_${lib}" SV_LIB_${lib}_NAME)
endforeach()
