name: Check for git lfs
on: [push, pull_request]
permissions:
  contents: write
jobs:
  check_git_lfs:
    runs-on: ubuntu-latest
    steps:
        - name: Check for large files without git lfs
          id: lfs_check
          uses: ppremk/lfs-warning@v3.2
          with:
            filesizelimit: 1MB
