name: Check for git lfs
on: [push, pull_request]
permissions:
  contents: write
jobs:
  check_git_lfs:
    runs-on: ubuntu-latest
    steps:
        - name: Check for large files without git lfs
          id: lfs_check
          uses: ppremk/lfs-warning@v3.2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            filesizelimit: 1MB

        - name: Notify if large files are found
          if: steps.lfs_check.outputs.warning != ''
          run: echo "Warning: The following large files are not tracked by Git LFS: ${{ steps.lfs_check.outputs.warning }}"
