# This workflow checks for large files that are not tracked with git lfs
name: Check for git lfs
on: [push, pull_request]
permissions:
  contents: write
jobs:
  check_git_lfs:
    runs-on: ubuntu-latest
    steps:
        - name: Check for large files without git lfs
          uses: ppremk/lfs-warning@v3.2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            filesizelimit: 1MB