name: macOS
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MacOS dependencies
        run: |
          brew reinstall -v gcc
          brew install -v cmake vtk openblas lapack mesa open-mpi qt
          brew install lcov
          sudo ln -s /usr/local/opt/qt5/mkspecs /usr/local/mkspecs
          sudo ln -s /usr/local/opt/qt5/plugins /usr/local/plugins
          # Install Miniconda
      - name: Install Miniconda
        run: |
          curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
      - name: Build svZeroDSolver
        run: |
          git clone https://github.com/SimVascular/svZeroDSolver.git
          cd svZeroDSolver
          mkdir build
          cd build
          cmake ..
          make -j2
      - name: Build svFSIplus
        run: |
          mkdir build
          cd build
          cmake -DENABLE_COVERAGE=ON -DENABLE_ARRAY_INDEX_CHECKING=ON -DENABLE_UNIT_TEST=ON ..
          make -j2
      - name: Install test dependencies
        run: |
          conda create -n svfsiplus python=3.9
          conda run -n svfsiplus pip install pytest pytest-cov pytest-mock numpy meshio pandas
      - name: Run integration tests
        run: |
          git lfs pull
          cd tests
          conda run -n svfsiplus pytest -rPv --durations=0
      - name: Run unit tests
        run: |
          cd build/svFSI-build/Source/svFSI
          ctest --verbose
