name: Integration
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    container: msalvad/ubuntu22_vtk9:v1
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Look at Docker image for Ubuntu 22.04
        run: |
          cat /etc/os-release
          ls
      - name: Build svFSIplus
        run: |
          mkdir build
          cd build
          cmake -DENABLE_COVERAGE=ON -DENABLE_ARRAY_INDEX_CHECKING=ON -DENABLE_UNIT_TEST=ON ..
          make -j2
      - name: Install test dependencies
        run: |
          conda create -n svfsiplus python=3.9
          conda run -n svfsiplus pip install pytest pytest-cov pytest-mock numpy meshio pandas
      - name: Run integration tests
        run: |
          git lfs pull
          cd tests
          conda run -n svfsiplus pytest -rPv --durations=0
      - name: Run unit tests
        run: |
          cd build/svFSI-build/Source/svFSI
          ctest --verbose
      - name: Generate code coverage
        if: startsWith(matrix.os, 'ubuntu-22.04')
        run: |
          cd build/svFSI-build
          make coverage
      - name: Save coverage report
        if: startsWith(matrix.os, 'ubuntu-22.04')
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: build/svFSI-build/coverage
      - name: Upload coverage reports to Codecov
        if: startsWith(matrix.os, 'ubuntu-22.04')
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}